trigger: none

pool:
  vmImage: 'windows-latest'
  
steps:

- task: NodeTool@0
  inputs:
    versionSpec: '18.12.1'
  displayName: 'Install Node.js'

- script: |
    npm install 
    npm run build
  displayName: 'Npm install and build'