trigger: 
- master

pool:
  vmImage: 'windows-latest'
  
steps:
- checkout: 'self'
  fetchDepth: 0

- task: NodeTool@0
  inputs:
    versionSpec: '18.12.1'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'install'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'subzone'
    scannerMode: 'CLI'
    configMode: 'file'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: AzureFileCopy@2
  inputs:
    SourcePath: 'build'
    azureSubscription: 'Azure subscription 1(836dac06-9190-4ca2-980f-c1fa69e59375)'
    Destination: 'AzureBlob'
    storage: 'careerbaseweudev'
    ContainerName: '$web'